#!/bin/bash
if [ ! -z $2 ]; then
  scp root@$1:/root/owasp_dependency_check/report/dependency-check-report.html $2
else
  scp root@$1:/root/owasp_dependency_check/report/dependency-check-report.html .
fi

